version: '3.8'

services:
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: music
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql

    node:
        image: node:20.9.0
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - '3000:3000'
        command: npm run production

volumes:
    mysql_data:
